# 写星号配置 是为了让其他工具可以读取该配置，实现匹配
# 匹配深度仅允许一层 写一个星号
# 如果写两个星号 会导致匹配范围过大 .vercel 内的垃圾文件也被匹配 误认为该文件夹也是工作区
packages:
  - "packages/*"
  - "demos/*"
  - "tests/*"
  - "docs/*"
  - "fork/*"
  - "vite-plugins/*"
  - "learn-create-compoents-lib/*"
  # 配置系列的依赖包 为了实现便捷快速的配置分发
  - "configs-package/*"

catalog:
  typescript: 5.9.2
  lodash-es: 4.17.21
  # vercel出现bug，安装 39.4.2 出现依赖冲突。多个项目内均出现该错误。
  # 故在此考虑人工锁死版本号。
  # vercel: 39.3.0
  vercel: 41.2.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - vitepress-carbon
  - vue-demi
