packages:
  - packages/*
  - demos/*
  - tests/*
  - docs/*
  - fork/*
  - vite-plugins/*
  - learn-create-compoents-lib/*
  - configs-package/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - simple-git-hooks
  - vitepress-carbon
  - vue-demi
