packages:
  - packages/*
  - demos/*
  - tests/*
  - docs/*
  - fork/*
  - vite-plugins/*
  - learn-create-compoents-lib/*
  - configs-package/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - simple-git-hooks
  - vitepress-carbon
  - vue-demi

overrides:
  "automd@^0.4.1": "0.4.0"
  "jiti@^2.4.2": "2.4.1"
