packages:
  - packages/*
  - demos/*
  - tests/*
  - docs/*
  - fork/*
  - vite-plugins/*
  - learn-create-compoents-lib/*
  - configs-package/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  simple-git-hooks: true
  vitepress-carbon: true
  workerd: true
