packages:
  - packages/*
  - demos/*
  - tests/*
  - docs/*
  - fork/*
  - vite-plugins/*
  - learn-create-compoents-lib/*
  - configs-package/*

# CI 必须从工作区配置读取此项，确保各包的 CLI 链接完整。
shamefullyHoist: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - simple-git-hooks
  - vitepress-carbon
  - vue-demi
