import { readFileSync, writeFileSync, realpathSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

/**
 * 确保当前工作目录解析到的 consola 包在 Node.js 24 下可被 ESM 正确导入。
 *
 * 背景：
 * consola@3.4.2 的 package.json 没有显式提供 index.js 入口。在 Node.js 24 的 ESM 解析路径中，
 * 当 exports 字段因任何原因（条件嵌套、平台差异、pnpm 的 isolated 结构）未命中时，会 fallback 到
 * legacyMainResolve，最终尝试 `consola/index.js` 并失败。
 *
 * 之前尝试用 pnpm patch 重写 package.json 在部分 CI 阶段（如 turbo 多次触发 prebuild）未稳定生效，
 * 因此改为直接创建 `index.js` 垫片，这是最简单、最确定、最跨平台的修复方式。
 *
 * 注意：
 * 此脚本在 `packages/utils` 的 `prebuild` 中运行，因此它看到的是 automd 实际能解析到的 consola 实例。
 */

// 与 patches/consola.patch 目标保持一致：当 Node 按 main 解析时，指向 ESM 入口。
const TARGET_MAIN = "./dist/index.mjs";
const TARGET_EXPORTS = {
	".": {
		types: "./dist/index.d.mts",
		import: "./dist/index.mjs",
		require: "./lib/index.cjs",
		default: "./dist/index.mjs",
	},
	"./browser": {
		import: { types: "./dist/browser.d.mts", default: "./dist/browser.mjs" },
		require: { types: "./dist/browser.d.cts", default: "./dist/browser.cjs" },
	},
	"./basic": {
		import: { types: "./dist/basic.d.mts", default: "./dist/basic.mjs" },
		require: { types: "./dist/basic.d.cts", default: "./dist/basic.cjs" },
	},
	"./core": {
		import: { types: "./dist/core.d.mts", default: "./dist/core.mjs" },
		require: { types: "./dist/core.d.cts", default: "./dist/core.cjs" },
	},
	"./utils": {
		import: { types: "./dist/utils.d.mts", default: "./dist/utils.mjs" },
		require: { types: "./dist/utils.d.cts", default: "./dist/utils.cjs" },
	},
};

const INDEX_JS_SHIM = `// Auto-generated by scripts/ensure-consola-patch.ts
// Re-exports consola ESM entry to satisfy Node.js 24 legacyMainResolve fallback.
export * from "./dist/index.mjs";
export { default } from "./dist/index.mjs";
`;

function resolveConsolaDir(): string {
	const req = createRequire(join(process.cwd(), "package.json"));
	// 解析 consola 入口，再向上取两级到包根目录（entry -> 入口文件 -> 包根）
	const entryPath = req.resolve("consola");
	const realEntry = realpathSync(entryPath);
	return dirname(dirname(realEntry));
}

function resolveAutomdConsolaDir(): string | undefined {
	const req = createRequire(join(process.cwd(), "package.json"));
	try {
		// automd 的 exports 没有导出 ./dist/cli.mjs，因此通过解析其主入口定位包根目录。
		// automd 的依赖（包括 consola）会放在 .pnpm/automd@*/node_modules/consola 下。
		const automdPath = req.resolve("automd");
		const automdDir = dirname(dirname(realpathSync(automdPath)));
		const consolaDir = join(automdDir, "node_modules", "consola");
		if (existsSync(consolaDir)) {
			return realpathSync(consolaDir);
		}
	} catch {
		// ignore
	}
	return undefined;
}

function fixPackageJson(pkgPath: string): boolean {
	const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
	const needsFix = pkg.main !== TARGET_MAIN || JSON.stringify(pkg.exports) !== JSON.stringify(TARGET_EXPORTS);
	if (needsFix) {
		pkg.main = TARGET_MAIN;
		pkg.exports = TARGET_EXPORTS;
		writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
		return true;
	}
	return false;
}

function ensureIndexJs(consolaDir: string): boolean {
	const indexPath = join(consolaDir, "index.js");
	if (!existsSync(indexPath) || readFileSync(indexPath, "utf-8") !== INDEX_JS_SHIM) {
		writeFileSync(indexPath, INDEX_JS_SHIM);
		return true;
	}
	return false;
}

function fixConsolaDir(consolaDir: string) {
	const pkgPath = join(consolaDir, "package.json");
	if (!existsSync(pkgPath)) {
		console.log(`[ensure-consola-patch] 跳过非 consola 目录: ${consolaDir}`);
		return;
	}
	const pkgFixed = fixPackageJson(pkgPath);
	const indexFixed = ensureIndexJs(consolaDir);
	const status = [pkgFixed ? "package.json" : null, indexFixed ? "index.js" : null].filter(Boolean).join(" + ");
	if (status) {
		console.log(`[ensure-consola-patch] 已修复 ${status}: ${consolaDir}`);
	} else {
		console.log(`[ensure-consola-patch] 已正确: ${consolaDir}`);
	}
}

function main() {
	const dirs = new Set<string>();

	// 1. 当前 workspace 包解析到的 consola（packages/utils 的直接依赖）
	try {
		dirs.add(resolveConsolaDir());
	} catch (e) {
		console.error("[ensure-consola-patch] 无法解析 consola:", e);
		process.exit(1);
	}

	// 2. automd 的依赖上下文可能解析到的 consola
	const automdConsolaDir = resolveAutomdConsolaDir();
	if (automdConsolaDir) {
		dirs.add(automdConsolaDir);
	}

	for (const dir of dirs) {
		fixConsolaDir(dir);
	}
}

main();
