/**
 * 修复 consola ESM 模块解析问题（Node.js + pnpm symlink 环境）
 *
 * 背景：
 * consola@3.x 移除了包根目录的 index.js 文件，完全依赖 package.json 的
 * "exports" 字段进行模块解析。但在某些 Node.js + pnpm + Linux 组合下，
 * ESM 解析器会回退到 legacyMainResolve，去查找一个物理上不存在的 index.js，
 * 导致 ERR_MODULE_NOT_FOUND，进而使 automd prebuild 失败、CI 流水线中断。
 *
 * 修复方式：
 * 在 consola 包根目录写入一个最小的 ESM 重导出垫片（index.js），
 * 指向真正的入口 ./dist/index.mjs，让 legacyMainResolve 能找到有效文件。
 *
 * 特性：
 * - 幂等：垫片已存在且内容正确则跳过
 * - 安全：仅在目标目录的 package.json 确认 name === "consola" 时才操作
 * - 递归：自动发现根目录及所有 workspace 包下的 consola 软链接，并追溯到真实目录
 * - 静默容错：consola 未安装或目录异常时不报错、不中断 install 流程
 *
 * 参考：https://github.com/ruan-cat/monorepo (CI fix 2026-06-30)
 */
import { existsSync, writeFileSync, readFileSync, realpathSync, lstatSync, readdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

/** 写入 consola 根目录的 ESM 垫片内容 */
const SHIM_CONTENT = `// Auto-generated by scripts/fix-consola-esm.ts
// ESM compatibility shim — re-exports the real entry point.
export * from './dist/index.mjs';
export { default } from './dist/index.mjs';
`;

/**
 * 判断给定的 consola 目录是否需要写入/重写垫片。
 * 会跟随符号链接追溯到真实目录，因此即使 pnpm 采用 isolated 安装也能命中 store。
 */
function resolveRealConsolaDir(consolaDir: string): string | undefined {
	try {
		// 跟随符号链接，定位 pnpm store 中的真实目录
		const realDir = realpathSync(consolaDir);
		if (!existsSync(realDir)) return undefined;

		const pkgJsonPath = join(realDir, "package.json");
		if (!existsSync(pkgJsonPath)) return undefined;

		const pkg = JSON.parse(readFileSync(pkgJsonPath, "utf-8")) as { name?: string };
		return pkg.name === "consola" ? realDir : undefined;
	} catch {
		return undefined;
	}
}

/**
 * 尝试为指定目录下的 consola 包补齐 index.js 垫片。
 *
 * @param consolaDir - consola 包所在目录（如 node_modules/consola）
 * @returns 是否实际写入了垫片（true = 新写入/重写，false = 已存在或不满足条件）
 */
export function fixConsola(consolaDir: string): boolean {
	const realDir = resolveRealConsolaDir(consolaDir);
	if (!realDir) return false;

	const indexJs = join(realDir, "index.js");

	// 垫片已存在且内容正确，无需重复写入
	if (existsSync(indexJs)) {
		try {
			const existing = readFileSync(indexJs, "utf-8");
			if (existing === SHIM_CONTENT) return false;
		} catch {
			// 读取失败时继续重写
		}
	}

	writeFileSync(indexJs, SHIM_CONTENT, "utf-8");
	return true;
}

/**
 * 递归查找指定根目录下的所有 consola 包目录。
 * 只在 node_modules 层级搜索，避免无差别遍历整个仓库。
 */
function findConsolaDirs(root: string): string[] {
	const dirs: string[] = [];
	const nodeModules = join(root, "node_modules");

	const candidates: string[] = [join(nodeModules, "consola")];

	// 额外扫描 packages、configs-package、vite-plugins 下的直接依赖
	const workspaceRoots = ["packages", "configs-package", "vite-plugins", "demos"];
	for (const rel of workspaceRoots) {
		const abs = join(root, rel);
		if (!existsSync(abs)) continue;
		try {
			const subdirs = readDirSync(abs);
			for (const sub of subdirs) {
				candidates.push(join(abs, sub, "node_modules", "consola"));
			}
		} catch {
			// ignore
		}
	}

	// 过滤出真实存在的候选目录
	for (const c of candidates) {
		if (existsSync(c)) dirs.push(c);
	}

	return dirs;
}

function readDirSync(path: string): string[] {
	try {
		return readdirSync(path, { withFileTypes: true })
			.filter((d) => d.isDirectory())
			.map((d) => d.name);
	} catch {
		return [];
	}
}

// ── 直接运行时执行修复（被 import 时不触发） ──

const isDirectRun = (() => {
	try {
		const scriptPath = fileURLToPath(import.meta.url);
		return process.argv[1] && resolve(process.argv[1]) === scriptPath;
	} catch {
		return false;
	}
})();

if (isDirectRun) {
	const __dirname = fileURLToPath(new URL(".", import.meta.url));
	const root: string = resolve(__dirname, "..");

	const targets = findConsolaDirs(root);
	const details: string[] = [];

	let fixed = 0;
	for (const dir of targets) {
		const realDir = resolveRealConsolaDir(dir);
		if (!realDir) continue;

		const indexJs = join(realDir, "index.js");
		const needsWrite = !existsSync(indexJs) || readFileSync(indexJs, "utf-8") !== SHIM_CONTENT;

		if (needsWrite) {
			writeFileSync(indexJs, SHIM_CONTENT, "utf-8");
			fixed++;
			details.push(`${dir} -> ${realDir}`);
		}
	}

	if (fixed > 0) {
		console.log(`[fix-consola-esm] 已补齐 ${fixed} 个 consola 的 index.js 垫片：`);
		for (const d of details) console.log(`  - ${d}`);
	} else {
		console.log("[fix-consola-esm] 所有 consola 目录的 index.js 垫片均已就绪");
	}
}
