/**
 * 修复 consola ESM 模块解析问题（Node.js + pnpm symlink 环境）
 *
 * 背景：
 * consola@3.x 移除了包根目录的 index.js 文件，完全依赖 package.json 的
 * "exports" 字段进行模块解析。但在某些 Node.js + pnpm + Linux 组合下，
 * ESM 解析器会回退到 legacyMainResolve，去查找一个物理上不存在的 index.js，
 * 导致 ERR_MODULE_NOT_FOUND，进而使 automd prebuild 失败、CI 流水线中断。
 *
 * 修复方式：
 * 在 consola 包根目录写入一个最小的 ESM 重导出垫片（index.js），
 * 指向真正的入口 ./dist/index.mjs，让 legacyMainResolve 能找到有效文件。
 *
 * 特性：
 * - 幂等：垫片已存在则跳过，不会重复写入
 * - 安全：仅在目标目录的 package.json 确认 name === "consola" 时才操作
 * - 静默容错：consola 未安装或目录异常时不报错、不中断 install 流程
 *
 * 参考：https://github.com/ruan-cat/monorepo (CI fix 2026-06-30)
 */
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** 写入 consola 根目录的 ESM 垫片内容 */
const SHIM_CONTENT = `// Auto-generated by scripts/fix-consola-esm.ts
// ESM 兼容垫片 —— 重导出到真正的入口文件
export * from './dist/index.mjs';
export { default } from './dist/index.mjs';
`;

/**
 * 尝试为指定目录下的 consola 包补齐 index.js 垫片。
 *
 * @param consolaDir - consola 包所在目录（如 node_modules/consola）
 * @returns 是否实际写入了垫片（true = 新写入，false = 已存在或不满足条件）
 */
export function fixConsola(consolaDir: string): boolean {
  const indexJs = join(consolaDir, 'index.js');

  // 垫片已存在，无需重复写入（幂等）
  if (existsSync(indexJs)) return false;

  // 必须有 package.json 才能确认这是一个合法的包目录
  const pkgJsonPath = join(consolaDir, 'package.json');
  if (!existsSync(pkgJsonPath)) return false;

  // 校验 package.json 的 name 字段，防止误操作其他包
  try {
    const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf-8')) as { name?: string };
    if (pkg.name !== 'consola') return false;
  } catch {
    return false;
  }

  writeFileSync(indexJs, SHIM_CONTENT, 'utf-8');
  return true;
}

// ── 直接运行时执行修复（被 import 时不触发） ──

const isDirectRun = (() => {
  try {
    const scriptPath = fileURLToPath(import.meta.url);
    return process.argv[1] && resolve(process.argv[1]) === scriptPath;
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  const __dirname = fileURLToPath(new URL('.', import.meta.url));
  const root: string = resolve(__dirname, '..');

  // 主要目标：shamefully-hoist 提升到根 node_modules 的 consola
  const targets: string[] = [join(root, 'node_modules', 'consola')];

  let fixed = 0;
  for (const dir of targets) {
    if (fixConsola(dir)) fixed++;
  }

  if (fixed > 0) {
    console.log(`[fix-consola-esm] 已补齐 ${fixed} 个 consola 的 index.js 垫片`);
  }
}
